2024-04-09 19:01:24,203 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 19:01:24,203 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Configure stats pid to 7982
2024-04-09 19:01:24,204 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-09 19:01:24,204 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-09 19:01:24,204 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 19:01:24,204 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 19:01:24,205 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 19:01:24,206 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-09 19:01:24,206 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 19:01:24,207 INFO    MainThread:7982 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_190124-j9bex67s/logs/debug.log
2024-04-09 19:01:24,208 INFO    MainThread:7982 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_190124-j9bex67s/logs/debug-internal.log
2024-04-09 19:01:24,209 INFO    MainThread:7982 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f29fc16a170>
2024-04-09 19:01:24,209 INFO    MainThread:7982 [wandb_init.py:init():561] calling init triggers
2024-04-09 19:01:24,209 INFO    MainThread:7982 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'epochs': 25, 'learning_rate': 0.0001, 'batch_size': 128}
2024-04-09 19:01:24,210 INFO    MainThread:7982 [wandb_init.py:init():611] starting backend
2024-04-09 19:01:24,210 INFO    MainThread:7982 [wandb_init.py:init():615] setting up manager
2024-04-09 19:01:24,215 INFO    MainThread:7982 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-09 19:01:24,216 INFO    MainThread:7982 [wandb_init.py:init():623] backend started and connected
2024-04-09 19:01:24,228 INFO    MainThread:7982 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-09 19:01:24,229 INFO    MainThread:7982 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-09 19:01:24,229 INFO    MainThread:7982 [wandb_init.py:init():715] updated telemetry
2024-04-09 19:01:24,245 INFO    MainThread:7982 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-09 19:02:54,266 ERROR   MainThread:7982 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-09 19:02:54,310 ERROR   MainThread:7982 [wandb_init.py:init():1199] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/russellsb/.cache/pypoetry/virtualenvs/data_science_for_business_package-muNh-jkR-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/russellsb/.cache/pypoetry/virtualenvs/data_science_for_business_package-muNh-jkR-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-09 19:06:54,696 INFO    MainThread:7982 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-09 19:06:54,735 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 19:06:54,736 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Configure stats pid to 7982
2024-04-09 19:06:54,737 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-09 19:06:54,737 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-09 19:06:54,738 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 19:06:54,739 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 19:06:54,739 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 19:06:54,740 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-09 19:06:54,741 INFO    MainThread:7982 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 19:06:54,742 INFO    MainThread:7982 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_190654-o0zsy5y5/logs/debug.log
2024-04-09 19:06:54,742 INFO    MainThread:7982 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_190654-o0zsy5y5/logs/debug-internal.log
2024-04-09 19:06:54,743 INFO    MainThread:7982 [wandb_init.py:init():561] calling init triggers
2024-04-09 19:06:54,744 INFO    MainThread:7982 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-09 19:06:54,744 INFO    MainThread:7982 [wandb_init.py:init():611] starting backend
2024-04-09 19:06:54,745 INFO    MainThread:7982 [wandb_init.py:init():615] setting up manager
2024-04-09 19:06:54,750 INFO    MainThread:7982 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-09 19:06:54,751 INFO    MainThread:7982 [wandb_init.py:init():623] backend started and connected
2024-04-09 19:06:54,763 INFO    MainThread:7982 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-09 19:06:54,763 INFO    MainThread:7982 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-09 19:06:54,764 INFO    MainThread:7982 [wandb_init.py:init():715] updated telemetry
2024-04-09 19:06:54,776 INFO    MainThread:7982 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-09 19:08:24,797 ERROR   MainThread:7982 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-09 19:08:24,831 ERROR   MainThread:7982 [wandb_init.py:init():1199] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/russellsb/.cache/pypoetry/virtualenvs/data_science_for_business_package-muNh-jkR-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/russellsb/.cache/pypoetry/virtualenvs/data_science_for_business_package-muNh-jkR-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
